name: brazkit
description: A util kit for flutter
version: 0.1.0
author: Emanuel Braz
homepage: intelibraz.com.br

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: 0.12.0+2
  shared_preferences: ^0.4.2
  url_launcher: ^5.1.0
  flutter_icons: ^0.1.4
  path_provider: ^0.4.1
  rxdart: ^0.22.0
  package_info: ^0.4.0+4
  # checar conexao internet, wifi...
  connectivity: ^0.4.3+2
  # biometria
  # local_auth: ^0.5.2+4
  #  sqflite: any

  flutter_udid: ^1.0.0
  device_id: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

