name: brazkit
description: A util kit for flutter
version: 0.1.0
author: Emanuel Braz
homepage: intelibraz.com.br

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^1.0.14
  shared_preferences: ^0.4.2
  url_launcher: ^5.1.0
  path_provider: ">=0.4.1"
  rxdart: ^0.22.0
  package_info: ^0.4.0+4  
  connectivity: ^0.4.5+3  

  flutter_icons:
    git:
      url: git://github.com/MagmaShared/flutter-icons.git
      ref: development

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

